version: 2
jobs:
  buildAndTest:
    docker:
      - image: node:9
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

workflows:
  version: 2
  buildAndPublish:
    jobs:
      - buildAndTest
